---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: blunix-os
description: This is my personal OS image.

base-image: ghcr.io/ublue-os/bazzite
image-version: latest

modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: dnf
    repos:
      cleanup: true
    install:
      packages:
        - https://repo.protonvpn.com/fedora-%OS_VERSION%-stable/protonvpn-stable-release/protonvpn-stable-release-1.0.3-1.noarch.rpm
        - kitty
        - neovim
    
  - type: default-flatpaks
    configurations:
      - scope: user
        repo:
          title: Flathub (user)
      - notify: true
        scope: system
        repo:
          title: Flathub (system)
        install:
          - org.prismlauncher.PrismLauncher
          - io.gitlab.librewolf-community
          - org.onlyoffice.desktopeditors
          - dev.vencord.Vesktop
          - org.vinegarhq.Sober
    
  - type: fonts
    fonts:
      nerd-fonts:
        - JetBrainsMono
  
  - type: signing
